import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    payload: 'src/payload.ts',
    'auto-block': 'src/auto-block.ts',
    'i18n/index': 'src/i18n/index.ts',
    'integrations/gcm': 'src/integrations/gcm.ts',
    'integrations/clarity': 'src/integrations/clarity.ts',
    'integrations/meta': 'src/integrations/meta.ts',
    'integrations/gtm': 'src/integrations/gtm.ts',
    'integrations/ga4': 'src/integrations/ga4.ts',
    'integrations/plausible': 'src/integrations/plausible.ts',
    'integrations/hotjar': 'src/integrations/hotjar.ts',
    'integrations/segment': 'src/integrations/segment.ts',
    'integrations/mixpanel': 'src/integrations/mixpanel.ts',
    'integrations/tiktok': 'src/integrations/tiktok.ts',
    'integrations/linkedin': 'src/integrations/linkedin.ts',
    'integrations/rdstation': 'src/integrations/rdstation.ts',
    'integrations/hubspot': 'src/integrations/hubspot.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  target: 'es2022',
  outDir: 'dist',
});
